theme: jekyll-theme-minimal

title: Alejandro Salazar Ramírez
description: Portafolio de Alejandro - Ciencia de Datos
name: Alejandro Salazar Ramírez
email: alezsr2505@gmail.com

github_username: aleewo
linkedin: www.linkedin.com/in/alejandro-salazar-ramírez

markdown: kramdown
plugins: [jekyll-remote-theme]
